import { PendingButton } from '@/components/pending-button';
import { db } from '@/lib/db';
import { deletePlan,deletePricing,savePlan,savePricing } from './actions';
const periods={MONTHLY:'ماهانه',QUARTERLY:'سه‌ماهه',YEARLY:'سالانه',ONE_TIME:'یک‌باره'} as const;
export default async function PlansAdmin({searchParams}:{searchParams:Promise<{error?:string}>}){const{error}=await searchParams;const plans=await db.plan.findMany({orderBy:{displayOrder:'asc'},include:{pricingVersions:{orderBy:{effectiveAt:'desc'}}}}).catch(()=>null);return <><header className="admin-title"><div><span className="eyebrow">PLANS & PRICING</span><h1>تعرفه‌ها و نسخه‌های قیمت</h1><p>مقادیر این صفحه فقط با تصمیم مدیر ثبت و منتشر می‌شوند.</p></div></header>{error&&<p className="form-error" role="alert">اطلاعات فرم معتبر نبود؛ ورودی‌ها را بررسی کنید.</p>}{plans===null?<section className="admin-card"><h2>دیتابیس در دسترس نیست</h2><p>برای مدیریت تعرفه، اتصال PostgreSQL محیط اجرا و migrationها را بررسی کنید.</p></section>:<>
 <section className="admin-card"><h2>پلن جدید</h2><PlanForm/></section>
 <div className="plan-admin-list">{plans.map(plan=><article className="admin-card" key={plan.id}><h2>{plan.title}</h2><PlanForm plan={plan}/><h3>نسخه‌های قیمت</h3>{plan.pricingVersions.map(price=><PricingForm key={price.id} price={price} planId={plan.id}/>)}<PricingForm planId={plan.id}/><form action={deletePlan}><input type="hidden" name="id" value={plan.id}/><PendingButton className="danger-button" pendingText="در حال حذف…">حذف پلن</PendingButton></form></article>)}</div>
 </>}</>}
function PlanForm({plan}:{plan?:any}){const limits=plan?.apiLimits as {daily?:number}|undefined;return <form action={savePlan} className="admin-form-grid">{plan&&<input type="hidden" name="id" value={plan.id}/>}<label>عنوان<input name="title" defaultValue={plan?.title} required/></label><label>slug<input name="slug" dir="ltr" defaultValue={plan?.slug} pattern="[a-z0-9-]+" required/></label><label>ترتیب نمایش<input name="displayOrder" type="number" min="0" defaultValue={plan?.displayOrder??0} required/></label><label>سقف روزانه API<input name="apiDailyLimit" type="number" min="0" defaultValue={limits?.daily}/></label><label className="wide">ویژگی‌ها، هر خط یک مورد<textarea name="features" rows={4} defaultValue={Array.isArray(plan?.features)?plan.features.join('\n'):''} required/></label><label className="check"><input name="active" type="checkbox" defaultChecked={plan?.active}/> فعال</label><label className="check"><input name="webAvailable" type="checkbox" defaultChecked={plan?.webAvailable??true}/> وب</label><label className="check"><input name="mobileAvailable" type="checkbox" defaultChecked={plan?.mobileAvailable}/> موبایل</label><PendingButton pendingText="در حال ذخیره…">{plan?'ذخیره تغییرات':'ساخت پلن'}</PendingButton></form>}
function PricingForm({planId,price}:{planId:string;price?:any}){const date=price?.effectiveAt?new Date(price.effectiveAt).toISOString().slice(0,16):'';return <form action={savePricing} className="pricing-admin-form"><input type="hidden" name="planId" value={planId}/>{price&&<input type="hidden" name="id" value={price.id}/>}<input aria-label="قیمت" name="price" type="number" min="0" placeholder="قیمت" defaultValue={price?.price?.toString()} required/><input aria-label="ارز" name="currency" dir="ltr" placeholder="IRT" defaultValue={price?.currency??'IRT'} required/><select aria-label="دوره پرداخت" name="billingPeriod" defaultValue={price?.billingPeriod??'MONTHLY'}>{Object.entries(periods).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><input aria-label="تخفیف" name="discount" type="number" min="0" max="100" step="0.01" placeholder="تخفیف %" defaultValue={price?.discount?.toString()}/><input aria-label="تاریخ اجرا" name="effectiveAt" type="datetime-local" defaultValue={date} required/><label className="check"><input name="active" type="checkbox" defaultChecked={price?.active}/> فعال</label><PendingButton className="small-action" pendingText="…">{price?'ذخیره':'افزودن قیمت'}</PendingButton>{price&&<button className="danger-button" formAction={deletePricing} type="submit">حذف</button>}</form>}
