import Link from 'next/link';
import { Activity, ArrowUpLeft, Bot, Calculator, ChartNoAxesCombined, ChevronLeft, CircleHelp, Code2, Gauge, GraduationCap, Layers3, Radio, Scale, ShieldAlert, ShieldCheck, ShoppingBag, Sparkles, WalletCards } from 'lucide-react';
import { MarketBoard } from '@/components/market-board';
import { HeroTicker } from '@/components/hero-ticker';
import { GoldCalculator } from '@/components/gold-calculator';
import { getSnapshot } from '@/server/quotes';

const previews=[
 {icon:Bot,title:'دستیار نوسان‌گیری',tag:'TRADING ASSISTANT',text:'داده، سناریو و ریسک را در یک گفت‌وگوی قابل پیگیری کنار هم می‌گذارد.',state:'در انتظار تعریف قطعی رفتار ایجنت'},
 {icon:ChartNoAxesCombined,title:'تحلیل توضیح‌پذیر',tag:'EXPLAINABLE',text:'هر خروجی باید ورودی، زمان داده، نسخهٔ مدل و دلیل قابل مشاهده داشته باشد.',state:'بدون مدل معتبر خروجی منتشر نمی‌شود'},
];
export default async function Home(){const snapshot=await getSnapshot();return <main id="main" className="shell">
 <div className="topline"><span><span className="status-dot"/> دیده‌بان هوشمند بازار ایران</span><span>{snapshot.mode==='demo'?'پیش‌نمایش محصول · دادهٔ نمونه و غیرزنده':'قیمت‌ها با زمان و منبع مشخص'}</span></div>
 <section className="hero"><div className="hero-copy hero-reveal"><span className="eyebrow gold-text"><span className="tiny-line"/> یک قدم آگاهانه‌تر</span><h1>بازار را واضح ببین.<br/><span className="gold-text">ریسک را قبل از تصمیم بشناس.</span></h1><p>طلا، ارز و ابزارهای مدیریت سرمایه در یک تجربهٔ ساده و فارسی؛ با منبع، زمان و منطق قابل بررسی.</p><div className="hero-actions"><Link href="/login" className="button">شروع تجربهٔ زرسیگنال <ArrowUpLeft size={18}/></Link><Link href="/methodology" className="text-link">روش کار را ببین <ChevronLeft size={16}/></Link></div><div className="decision-strip"><span><Gauge size={15}/><b>الان چه خبر است؟</b><small>نبض بازار</small></span><span><CircleHelp size={15}/><b>چرا؟</b><small>منبع و روش</small></span><span><ShieldAlert size={15}/><b>ریسک چیست؟</b><small>ابزار آموزشی</small></span></div><div className="hero-features"><span><ShieldCheck size={16}/> منبع شفاف</span><span><Activity size={16}/> پایش دوره‌ای</span><span><Layers3 size={16}/> نگاه یکپارچه</span></div></div>
 <div className="radar-art"><div className="radar-grid"/><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit orbit-three"/><div className="radar-ray"/><span className="radar-label label-top">XAU / GOLD</span><span className="radar-label label-bottom">MARKET INTELLIGENCE</span><div className="radar-center"><Activity size={38}/><strong>رادار بازار</strong><small>شفافیت در یک نگاه</small></div><span className="radar-token token-gold">Au<small>طلا</small></span><span className="radar-token token-silver">Ag<small>نقره</small></span><span className="radar-token token-dollar">$<small>دلار</small></span><div className="radar-caption"><span className="status-dot"/> سه بازار، یک تصویر روشن</div></div></section>
 <HeroTicker quotes={snapshot.quotes} mode={snapshot.mode}/>
 <section id="bubbles" className="section-reveal"><div className="section-heading"><div><span className="eyebrow">FAIR VALUE PREVIEW</span><h2>فاصلهٔ قیمت تا ارزش محاسبه‌شده</h2></div><Link className="text-link" href="/methodology">روش محاسبه <ArrowUpLeft size={15}/></Link></div><div className="bubble-grid">{['طلای آبشده','نقره','دلار'].map((name,i)=><article className="panel bubble-card" key={name}><span className="eyebrow">۰{i+1}</span><h3>{name}</h3><div className="bubble-value">—<span>در انتظار فرمول تأییدشده</span></div><p>پس از ثبت specification و اعتبارسنجی داده، نتیجه همراه با دلیل نمایش داده می‌شود.</p></article>)}</div><p className="subtle-note">این بخش فعلاً هیچ حباب یا ارزش نظری را حدس نمی‌زند.</p></section>
 <MarketBoard initial={snapshot}/>
 <section className="preview-grid section-reveal">{previews.map(({icon:Icon,...item})=><article className="panel product-preview" key={item.title}><Icon size={25}/><span className="eyebrow">{item.tag}</span><h2>{item.title}</h2><p>{item.text}</p><strong>{item.state}</strong></article>)}</section>
 <section className="feature-band"><div><Calculator/><span className="eyebrow">PROFESSIONAL CALCULATOR</span><h2>ماشین‌حساب حرفه‌ای طلا</h2><p>ورودی‌ها و واحدها روشن می‌مانند؛ مالیات، عیار و قواعد معامله پس از تأیید Product Spec افزوده می‌شوند.</p></div><GoldCalculator/></section>
 <section className="capability-grid section-reveal"><article className="panel"><WalletCards/><h2>حسابداری طلای آبشده</h2><p>دفتر معامله، مانده و گزارش قابل ردیابی؛ منطق حسابداری تا رفع SPEC_BLOCKER فعال نمی‌شود.</p><span className="status-chip">طراحی محصول</span></article><article className="panel"><Scale/><h2>مدیریت سرمایه و ریسک</h2><p>آموزش افت سرمایه و محاسبهٔ عمومی مبلغ ریسک، اندازه موقعیت و نسبت ریسک به بازده.</p><Link href="/risk-management">بازکردن ابزارهای آموزشی <ArrowUpLeft size={15}/></Link></article></section>
 <section className="api-callout panel"><Code2/><div><span className="eyebrow">ZARSIGNAL API</span><h2>داده برای محصول شما</h2><p>دسترسی نسخه‌بندی‌شده با کلید، سهمیه و کنترل اشتراک؛ دادهٔ نمایشی همیشه برچسب دارد.</p></div><code dir="ltr">GET /api/v1/quotes</code><Link className="button" href="/developers">مستندات API</Link></section>
 <section className="plans-preview"><div><Sparkles/><span className="eyebrow">PLANS</span><h2>پلن متناسب با شیوهٔ استفاده</h2><p>تعرفه‌ها پس از تعریف مدیر از دیتابیس نمایش داده می‌شوند؛ این نسخه قیمت ساختگی منتشر نمی‌کند.</p></div><Link href="/pricing" className="button">مشاهدهٔ پلن‌ها <ArrowUpLeft size={16}/></Link></section>
 <section className="trust-grid"><article><ShieldCheck/><h3>روش و منبع روشن</h3><p>زمان دریافت، تازگی داده و نسخهٔ مدل بخشی از خروجی است.</p></article><article><GraduationCap/><h3>آموزش پیش از ابزار</h3><p>کاربر باید محدودیت ابزار و ریسک تصمیم را ببیند.</p></article><article><Radio/><h3>عدم انتشار حدس</h3><p>فرمول تأییدنشده به عنوان تحلیل نمایش داده نمی‌شود.</p></article></section>
 <section className="marketplace-teaser panel"><ShoppingBag/><div><span className="eyebrow">MARKETPLACE · آینده</span><h2>بازار ابزار و تجربه‌های تخصصی</h2><p>فقط یک پیش‌نمایش از مسیر آینده؛ عرضهٔ عمومی پس از تثبیت هستهٔ محصول.</p></div></section>
 <section className="faq"><span className="eyebrow">FAQ</span><h2>پرسش‌های پرتکرار</h2>{[['داده‌ها زنده هستند؟',snapshot.mode==='demo'?'خیر. این نسخه دادهٔ نمونه و غیرزنده را با برچسب روشن نمایش می‌دهد.':'هر رکورد زمان و منبع دریافت دارد.'],['زرسیگنال سیگنال خرید می‌دهد؟','خیر. ابزارها اطلاعات و محاسبات توضیح‌پذیر ارائه می‌کنند و تضمین نتیجه ندارند.'],['فرمول‌های طلا کجا هستند؟','فقط پس از تأیید specification و تست حالت‌های مرزی وارد محصول می‌شوند.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
 <section className="legal-risk"><ShieldAlert/><div><h2>تصمیم مالی مسئولیت و ریسک دارد.</h2><p>محتوای زرسیگنال توصیهٔ خرید یا فروش و تضمین سود نیست. دادهٔ ناقص، تأخیردار یا خطای محاسباتی ممکن است رخ دهد؛ منبع و زمان را پیش از تصمیم بررسی کنید.</p></div></section>
 </main>}
