'use client';
import { useMemo, useState } from 'react';
import { positionSize, riskAmount, riskReward } from '@/lib/risk';
const n=(value:string)=>Number(value.replace(/,/g,''));
const show=(result:ReturnType<typeof riskAmount>,digits=0)=>result.ok?new Intl.NumberFormat('fa-IR',{maximumFractionDigits:digits}).format(result.value):result.error;
export function RiskCalculators(){const[capital,setCapital]=useState('');const[percent,setPercent]=useState('');const[amount,setAmount]=useState('');const[loss,setLoss]=useState('');const[entry,setEntry]=useState('');const[stop,setStop]=useState('');const[target,setTarget]=useState('');const risk=useMemo(()=>riskAmount(n(capital),n(percent)),[capital,percent]);const size=useMemo(()=>positionSize(n(amount),n(loss)),[amount,loss]);const rr=useMemo(()=>riskReward(n(entry),n(stop),n(target)),[entry,stop,target]);return <div className="risk-tools">
 <article className="panel risk-tool"><span className="eyebrow">RISK AMOUNT</span><h2>مبلغ در معرض ریسک</h2><p>سرمایه و درصدی را که خودتان تعیین کرده‌اید وارد کنید.</p><label>کل سرمایه<input inputMode="decimal" value={capital} onChange={e=>setCapital(e.target.value)}/></label><label>درصد ریسک<input inputMode="decimal" value={percent} onChange={e=>setPercent(e.target.value)}/></label><output>{show(risk)}</output></article>
 <article className="panel risk-tool"><span className="eyebrow">POSITION SIZE</span><h2>اندازهٔ موقعیت عمومی</h2><p>این محاسبه مستقل از نوع دارایی است و واحد خروجی تابع ورودی شماست.</p><label>مبلغ ریسک<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>زیان هر واحد<input inputMode="decimal" value={loss} onChange={e=>setLoss(e.target.value)}/></label><output>{show(size,4)}</output></article>
 <article className="panel risk-tool"><span className="eyebrow">RISK / REWARD</span><h2>نسبت ریسک به بازده</h2><p>فقط نسبت فاصله‌ها محاسبه می‌شود و معنای توصیهٔ معاملاتی ندارد.</p><label>قیمت ورود<input inputMode="decimal" value={entry} onChange={e=>setEntry(e.target.value)}/></label><label>حد توقف<input inputMode="decimal" value={stop} onChange={e=>setStop(e.target.value)}/></label><label>هدف<input inputMode="decimal" value={target} onChange={e=>setTarget(e.target.value)}/></label><output>{rr.ok?`${new Intl.NumberFormat('fa-IR',{maximumFractionDigits:2}).format(rr.value)} : ۱`:rr.error}</output></article>
 </div>}
