CREATE TYPE "Role" AS ENUM ('ADMIN', 'USER', 'HOME_TRADER', 'PROFESSIONAL_TRADER', 'API_CUSTOMER');
ALTER TABLE "User" ADD COLUMN "role" "Role" NOT NULL DEFAULT 'USER';
CREATE INDEX "User_role_idx" ON "User"("role");
